# language: node_js
# node_js: stable

# cache:
#     directories:
#         - ./node_modules

# before_deploy:
#     - sudo apt-get install zip unzip
#     - 'npm run fetch-latest'
#     - 'npm run parse'

# deploy:
#     provider: pages
#     skip_cleanup: true
#     github_token: $GITHUB_TOKEN
#     # local_dir: docs
#     on:
#         branch: master
