language: node_js
node_js: stable

cache:
    directories:
        - ./node_modules

git:
    depth: 2

before_deploy:
    - 'npm run build'

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: data
    on:
        branch: master
